/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState, useEffect } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF } from '@react-three/drei/useGLTF'

import { useAnimations } from '@react-three/drei/useAnimations'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/visual.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Circle" rotation={[0, 0, 0.1]}>
        <mesh
          name="Plane"
          material={nodes.Plane.material}
          geometry={nodes.Plane.geometry}
          morphTargetDictionary={nodes.Plane.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane.morphTargetInfluences}
        />
        <mesh
          name="Plane001"
          material={nodes.Plane001.material}
          geometry={nodes.Plane001.geometry}
          morphTargetDictionary={nodes.Plane001.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane001.morphTargetInfluences}
        />
        <mesh
          name="Plane002"
          material={nodes.Plane002.material}
          geometry={nodes.Plane002.geometry}
          morphTargetDictionary={nodes.Plane002.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane002.morphTargetInfluences}
        />
        <mesh
          name="Plane003"
          material={nodes.Plane003.material}
          geometry={nodes.Plane003.geometry}
          morphTargetDictionary={nodes.Plane003.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane003.morphTargetInfluences}
        />
        <mesh
          name="Plane004"
          material={nodes.Plane004.material}
          geometry={nodes.Plane004.geometry}
          morphTargetDictionary={nodes.Plane004.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane004.morphTargetInfluences}
        />
        <mesh
          name="Plane005"
          material={nodes.Plane005.material}
          geometry={nodes.Plane005.geometry}
          morphTargetDictionary={nodes.Plane005.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane005.morphTargetInfluences}
        />
        <mesh
          name="Plane006"
          material={nodes.Plane006.material}
          geometry={nodes.Plane006.geometry}
          morphTargetDictionary={nodes.Plane006.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane006.morphTargetInfluences}
        />
        <mesh
          name="Plane007"
          material={nodes.Plane007.material}
          geometry={nodes.Plane007.geometry}
          morphTargetDictionary={nodes.Plane007.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane007.morphTargetInfluences}
        />
        <mesh
          name="Plane008"
          material={nodes.Plane008.material}
          geometry={nodes.Plane008.geometry}
          morphTargetDictionary={nodes.Plane008.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane008.morphTargetInfluences}
        />
        <mesh
          name="Plane009"
          material={nodes.Plane009.material}
          geometry={nodes.Plane009.geometry}
          morphTargetDictionary={nodes.Plane009.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane009.morphTargetInfluences}
        />
        <mesh
          name="Plane010"
          material={nodes.Plane010.material}
          geometry={nodes.Plane010.geometry}
          morphTargetDictionary={nodes.Plane010.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane010.morphTargetInfluences}
        />
        <mesh
          name="Plane011"
          material={nodes.Plane011.material}
          geometry={nodes.Plane011.geometry}
          morphTargetDictionary={nodes.Plane011.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane011.morphTargetInfluences}
        />
        <mesh
          name="Plane012"
          material={nodes.Plane012.material}
          geometry={nodes.Plane012.geometry}
          morphTargetDictionary={nodes.Plane012.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane012.morphTargetInfluences}
        />
        <mesh
          name="Plane013"
          material={nodes.Plane013.material}
          geometry={nodes.Plane013.geometry}
          morphTargetDictionary={nodes.Plane013.morphTargetDictionary}
          morphTargetInfluences={nodes.Plane013.morphTargetInfluences}
        />
      </group>
      <mesh
        name="Cube"
        material={materials.Material}
        geometry={nodes.Cube.geometry}
        morphTargetDictionary={nodes.Cube.morphTargetDictionary}
        morphTargetInfluences={nodes.Cube.morphTargetInfluences}
        position={[0, 5.25, 0]}
        rotation={[0, -1.57, 0]}
      />
    </group>
  )
}

useGLTF.preload('/visual.glb')
